### ISSUE TITLE
Chart having odd first item in array

### ISSUE THREAD

**Issue by swantzter** [the-tricktionary/android#5]
There is an error caused by the `data[j] - data[j-1]` on the first entry which leaves a gap in the chart (as data[-1] doesn't exist)

On the web I currently solve this by removing that item from the array, optimal tough would be to have it work as if `data[-1] = 0`

![screenshot_20160815-163847](https://cloud.githubusercontent.com/assets/10356719/17668133/38e5df9a-6308-11e6-862f-57a102c91054.png)

**Comment by dylan-plummer** [comment]
Silly off by one error by me, fixed
